@startuml
class productScan {
    +int count
    +JSONObject json
    +String name
    +productScanner(String input, JSONArray subjects)
    +input.equalsIgnoreCase(name)
}

class App {
    +JSONParser parser
    +Object obj
    +JSONArray subjects
    +BufferedReader(new InputStreamReader(System.in)
    +productScanner(input, subjects)
}

productScan <|-- App
@enduml