@startuml
class nameSorter {
  +FileWriter(output)
  +namesReader(Scanner input, ArrayList<String> names)
  +names.add(input.nextLine())
  +namesOutput(ArrayList<String> names)
}

class App {
  +names: ArrayList<String>
  +main(String[])
  +Scanner(inputFile)
  +nameSorter.namesReader(inputFile, names)
  +names.sort(String.CASE_INSENSITIVE_ORDER)
  +nameSorter.namesOutput(names)

}

nameSorter <|-- App
@enduml