@startuml
class websiteGenerator {
  +String currentPath
  +File website
  +FileWriter bodyWriter
  +System.getProperty("user.dir")
  +File(currentPath)
  +bodyWriter()
}

class App {
  +String author, siteName
  +char js, css
  +main(String[])
  +Scanner(input)
  +websiteWriter(author, siteName, js, css)
}

websiteGenerator <|-- App
@enduml