@startuml
class fileEditor {
    +editedFileOutput(String output_file_name, String contents)
    +FileWriter(output_file_name)
    +contents.replaceAll("utilize", "use")
    +output.write(contents)
}

class App {
    +Scanner userInput
    +Scanner inputFile
    +String text_lines
    +StringBuilder sb
    +editedFileOutput(output_file_name, contents)
}

fileEditor <|-- App
@enduml